spring:
  application:
    name: jpa
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

  jpa.hibernate.naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
debug: true

#  jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#  jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl